version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./my_database_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=penmind
      - POSTGRES_USER=penmind_user
      - POSTGRES_PASSWORD=KhYA334URDtPrU0oLYzW8QbxQWXXZVdv
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
#      - static_root:/code/static_root
    environment:
      - SECRECT_KEY=a5958fb3723b2e77787ed08bec37d9c0
      - DEBUG=False
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  static_root: