version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=penmind
      - POSTGRES_USER=penmind_user
      - POSTGRES_PASSWORD=KhYA334URDtPrU0oLYzW8QbxQWXXZVdv
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - static_root:/code/static
    ports:
      - "8000:8000"
    depends_on:
      - db
volumes:
  static_root: